-- AUTO-GENERATED from CHANGELOG.md -- do not edit by hand.
-- Regenerated by package-release.ps1 (and the release workflow) at package time.
local _, TCC = ...
TCC.CHANGELOG = [==[
# Twisteds Combat Cues - What's New

## 1.2.0-beta.2

- **[BUG FIX]** Fixed error spam in combat and dungeons ("secret value" Lua errors).
- **[BUG FIX]** Fixed scrolling in the Cue Manager - it previously only worked on the
  Getting Started page. Mouse wheel and the scrollbar work everywhere now.
- **[BUG FIX]** Focus call-out now works in combat. Your Party/Raid chat message was
  being blocked mid-fight; it sends reliably now.
- **[BUG FIX]** Range cues work in instances again. "Healer/Tank out of range" alerts
  now work in dungeons, raids, and scenarios, and the debug screen shows the real
  distance in yards.
- **[BUG FIX]** Marker palette remembers itself - if you close the on-screen marker
  bar, it stays closed after a reload (before, it kept coming back).
- **[NEW]** "What's New" page - browse recent updates right in the addon
  (sidebar > What's New).
- **[NEW]** "Tank in range" readout added to the debug screen.
- **[NEW]** Discord link in the footer - click it to copy an invite to the community
  server.
- **[CHANGE]** Focus call-out no longer inserts the target's name. Blizzard now hides
  unit names in combat, so the call-out shows just your marker icon (e.g. "Focus {skull}").

## 1.2.0-beta.1

- **[NEW]** First public beta.
]==]
